import type { Metadata } from "next";
import { Bebas_Neue, Barlow, Permanent_Marker } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { fetchTournamentStartDate } from '@/lib/contentful';
import { TournamentDateProvider } from '@/context/TournamentDateContext';

const permanentMarker = Permanent_Marker({
  subsets: ['latin'],
  weight: '400',
});

const barlow = Barlow({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-barlow',
});

const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bebas',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tournamentDate = await fetchTournamentStartDate(); 
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${barlow.variable} ${permanentMarker} antialiased`}
      >
        <TournamentDateProvider date={tournamentDate}>
          <Navbar />
          {children}
          <Footer />
        </TournamentDateProvider>
      </body>
    </html>
  );
}
